<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Logic\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Select.HtmlToPdf" Version="26.2.0" />
    <PackageReference Include="Select.Pdf" Version="26.2.0" />
    <PackageReference Include="Select.Pdf.NetCore" Version="26.2.0" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetFramework" Version="1.0.119" />
  </ItemGroup>

</Project>